--DATA WAREHOUSE ANALYTICS PROJECT FOR PORTFOLIO

--1.Dimensions Exploration
--1.1. Exploring all countries the customers come from

SELECT DISTINCT country 
from DataWarehouseAnalytics.gold.dim_customers

--1.2.Exploring all product categories "The Major Divisions"

SELECT DISTINCT category, subcategory, product_name
FROM DataWarehouseAnalytics.gold.dim_products
ORDER BY 1,2,3

--1.3.Exploring Dates. Find the date of the first and last order

SELECT 
MIN(order_date) AS First_OrderDate,
MAX(order_date) AS Last_OrderDate
FROM DataWarehouseAnalytics.gold.fact_sales

--1.4.Find how many years of orders the Warehouse has stored in its database

SELECT 
MIN(order_date) AS First_OrderDate,
MAX(order_date) AS Last_OrderDate,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS Total_Years_of_Orders
FROM DataWarehouseAnalytics.gold.fact_sales

--1.5.Find the youngest and oldest customer

SELECT 
MIN(birthdate) AS Oldest_Customer,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS Oldest_Age,
MAX(birthdate) AS Youngest_Customer,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS Youngest_Age
FROM DataWarehouseAnalytics.gold.dim_customers

--2.Exploring Measures
--2.1.Find the Total Sales
--2.2.Find how many items are sold
--2.3.Find the average selling price 

SELECT 
SUM(sales_amount) as Total_Sales,
SUM(quantity) AS Total_Items_Sold,
AVG(price) AS Average_Selling_Price,
COUNT(DISTINCT(order_number)) AS Total_Number_of_Orders
FROM DataWarehouseAnalytics.gold.fact_sales

--2.4.Find the Total Number of Products

SELECT 
COUNT(DISTINCT(product_id)) AS Total_Number_of_Products
from DataWarehouseAnalytics.gold.dim_products

--2.5.Find the Total Number of Customers 

SELECT 
COUNT(DISTINCT(customer_key)) AS Total_Number_of_Customers 
FROM DataWarehouseAnalytics.gold.dim_customers

--2.6.Find the Total Number of Customers who has placed an order

SELECT 
COUNT(DISTINCT(customer_key)) AS Total_Number_of_Customers_PlacedOrder 
FROM DataWarehouseAnalytics.gold.fact_sales

--3.Magnitudes Analysis 

--3.1.Find the total customers by countries 

SELECT 
country,
COUNT(DISTINCT(customer_id)) AS Total_Customers_by_Countries
FROM DataWarehouseAnalytics.gold.dim_customers
GROUP BY country
ORDER BY COUNT(DISTINCT(customer_id)) DESC

--3.2.Find the total customers by gender

SELECT 
gender,
COUNT(DISTINCT(customer_id)) AS Total_Customers_by_Gender
FROM DataWarehouseAnalytics.gold.dim_customers
GROUP BY gender

--3.3.Find the total products by categories

SELECT 
category,
COUNT(DISTINCT(product_name)) AS Total_Products_by_Category
FROM DataWarehouseAnalytics.gold.dim_products
GROUP BY category

--3.4.Find the average cost for each category.Order from largest to smallest.Remove Nulls

SELECT 
category,
AVG(cost) AS Average_Cost_by_Category
FROM DataWarehouseAnalytics.gold.dim_products
WHERE category IS NOT NULL
GROUP BY category
ORDER BY AVG(cost) DESC

--3.5.Find the total profit generated by each category

SELECT 
P.category,
SUM(sales_amount) AS Total_Profit_by_Category
FROM  DataWarehouseAnalytics.gold.fact_sales as S
LEFT JOIN  DataWarehouseAnalytics.gold.dim_products AS P
ON P.product_key = S.product_key
GROUP BY P.category
ORDER BY Total_Profit_by_Category DESC

--3.6.Find the total profit generated by each customer

SELECT 
C.customer_key,
C.first_name,
C.last_name,
SUM(sales_amount) AS Total_Profit_by_Customer
FROM DataWarehouseAnalytics.gold.fact_sales AS S
LEFT JOIN  DataWarehouseAnalytics.gold.dim_customers AS C
ON C.customer_key = S.customer_key
GROUP BY 
C.customer_key,
C.first_name,
C.last_name
ORDER BY SUM(sales_amount) DESC

--.3.7.Find the distribution of sold items across countries 

SELECT 
C.country,
P.subcategory,
SUM(quantity) AS Distribution_of_SoldItems_by_Countries
FROM DataWarehouseAnalytics.gold.fact_sales AS S
LEFT JOIN DataWarehouseAnalytics.gold.dim_products AS P
ON P.product_key = S.product_key
LEFT JOIN DataWarehouseAnalytics.gold.dim_customers AS C
ON S.customer_key = C.customer_key
GROUP BY C.country, P.subcategory 
ORDER BY C.country, Distribution_of_SoldItems_by_Countries DESC

--4.Ranking Analysis 
--4.1.What are the 5 top products with the highest profits?

SELECT TOP (5) 
P.product_name,
SUM(sales_amount) AS Highest_Profit
FROM DataWarehouseAnalytics.gold.fact_sales AS S
LEFT JOIN DataWarehouseAnalytics.gold.dim_products AS P
ON S.product_key = P.product_key
GROUP BY P.product_name
ORDER BY Highest_Profit DESC

--4.2.What are the 5 top products with the highest profits? Use ranking.

SELECT *
FROM (
	SELECT 
	P.product_name,
	SUM(S.sales_amount) AS Highest_Profit,
	DENSE_RANK() OVER (ORDER BY SUM(S.sales_amount) DESC) AS Profit_Product_Rank
	FROM DataWarehouseAnalytics.gold.fact_sales AS S
	LEFT JOIN DataWarehouseAnalytics.gold.dim_products AS P
	ON S.product_key = P.product_key
	GROUP BY P.product_name)t
WHERE Profit_Product_Rank <= 5


--4.3.Find the 5 worst performing products in terms of sales

SELECT TOP (5) 
P.product_name,
SUM(sales_amount) AS Lowest_Profit
FROM DataWarehouseAnalytics.gold.fact_sales AS S
LEFT JOIN DataWarehouseAnalytics.gold.dim_products AS P
ON S.product_key = P.product_key
GROUP BY P.product_name
ORDER BY Lowest_Profit ASC


--4.5.Find the top 10 customers who have generated the highest revenue 

SELECT*
FROM (
	SELECT 
	C.first_name,
	C.last_name,
	SUM(sales_amount) AS Highest_Revenue_Customer,
	DENSE_RANK() OVER(ORDER BY SUM(sales_amount) DESC) AS Customer_Rank_by_Sales
	FROM DataWarehouseAnalytics.gold.fact_sales AS S
	LEFT JOIN DataWarehouseAnalytics.gold.dim_customers AS C
	ON S.customer_key = C.customer_key
	GROUP BY
	C.first_name,
	C.last_name)t
WHERE Customer_Rank_by_Sales <= 10

--5.Analyzing changes over time 
--5.1.Analyze sales changes over time 

SELECT
YEAR(order_date) AS Order_Year, 
MONTH(order_date) AS Order_Month,
FORMAT(order_date, 'yyyy-MMM') AS Order_Date_with_YearMonth,
(SUM(sales_amount)) AS Total_Sales_by_Date,
COUNT(DISTINCT(customer_key)) AS Total_Customers,
SUM(quantity) AS Total_Quantity
FROM DataWarehouseAnalytics.gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date), MONTH(order_date),FORMAT(order_date, 'yyyy-MMM')
ORDER BY YEAR(order_date), MONTH(order_date), FORMAT(order_date, 'yyyy-MMM')

--6.Cumulative Analysis 
--6.1.Find the total sales per month and the running total of sales over time per year

SELECT
Order_Month,
Total_Sales_by_Date,
SUM(Total_Sales_by_Date) OVER (PARTITION BY YEAR (Order_Month) ORDER BY Order_Month) AS Running_Total_Sales_by_Year,
AVG_price,
AVG(avg_price) OVER (PARTITION BY YEAR (Order_Month) ORDER BY Order_Month) AS Moving_AVG_Price_by_Year
FROM (
	SELECT
	DATETRUNC(month, order_date) AS Order_Month,
	SUM(sales_amount) AS Total_Sales_by_Date,
	AVG(price) AS AVG_price
	FROM DataWarehouseAnalytics.gold.fact_sales
	WHERE order_date IS NOT NULL
	GROUP BY DATETRUNC(month, order_date))t


--7.Performance Analysis 
--7.1.Analyze the yearly performance of products by comparing each product's sales to its
--average sales performance and the previous year's sales

WITH yearly_product_sales AS (
SELECT 
YEAR(S.order_date) AS Order_Year,
P.product_name,
SUM(S.sales_amount) AS Total_Product_Sales
FROM DataWarehouseAnalytics.gold.fact_sales AS S
LEFT JOIN DataWarehouseAnalytics.gold.dim_products AS P
ON S.product_key = P.product_key
WHERE S.order_date IS NOT NULL
GROUP BY
YEAR(S.order_date),
P.product_name
)

SELECT 
Order_Year,
product_name,
Total_Product_Sales,
AVG(Total_Product_Sales) OVER(PARTITION BY product_name) AS AVG_Product_Sales,
Total_Product_Sales - AVG(Total_Product_Sales) OVER(PARTITION BY product_name) AS Difference_AVG,
CASE
WHEN Total_Product_Sales - AVG(Total_Product_Sales) OVER(PARTITION BY product_name) > 0 THEN 'Above AVG'
WHEN Total_Product_Sales - AVG(Total_Product_Sales) OVER(PARTITION BY product_name) < 0 THEN 'Below AVG' 
ELSE 'AVG'
END AS Product_Performance,
LAG(Total_Product_Sales) OVER (PARTITION BY product_name ORDER BY Order_Year) AS TotalSales_Performance_by_Previous_Year,
Total_Product_Sales - LAG(Total_Product_Sales) OVER (PARTITION BY product_name ORDER BY Order_Year) AS Difference_with_Previous_Year,
CASE
WHEN Total_Product_Sales - LAG(Total_Product_Sales) OVER (PARTITION BY product_name ORDER BY Order_Year) > 0 THEN 'Increase'
WHEN Total_Product_Sales - LAG(Total_Product_Sales) OVER (PARTITION BY product_name ORDER BY Order_Year) < 0 THEN 'Decrease' 
ELSE 'No Change'
END AS Previous_Year_Chage_Evaluation
FROM yearly_product_sales
ORDER BY product_name, Order_Year

--7.2.Find the categories which contribute the most to overall sales 

WITH Total_Sales_By_Cat AS (
SELECT 
P.category,
SUM(S.sales_amount) AS Total_Sales_Amount
FROM DataWarehouseAnalytics.gold.fact_sales AS S
LEFT JOIN DataWarehouseAnalytics.gold.dim_products AS P
ON S.product_key = P.product_key
GROUP BY P.category
)

SELECT 
category,
Total_Sales_Amount,
SUM(Total_Sales_Amount) OVER () AS Total_Sales_Across_AllCat, 
CONCAT(ROUND((CAST(Total_Sales_Amount  AS FLOAT)/SUM(Total_Sales_Amount) OVER ()) * 100, 2), '%') AS Perct_Contrib
FROM Total_Sales_By_Cat
ORDER BY Total_Sales_Amount DESC

--8.Data Segmentation 
--8.1.Segment products into cost ranges and count how many products fall into each segment 

WITH Cost_Range_Product AS (
SELECT 
product_name,
cost,
CASE
WHEN cost < 100 THEN 'Below 100'
WHEN cost BETWEEN 100 AND 500 THEN '100-500'
WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
ELSE 'Above 1000'
END AS Cost_Range
FROM DataWarehouseAnalytics.gold.dim_products
)

SELECT
Cost_Range,
COUNT(DISTINCT (product_name)) AS Ranges_Count
FROM Cost_Range_Product 
GROUP BY Cost_Range
ORDER BY Ranges_Count DESC

--8.1.Group customers into three segments based on their spending behavior:
--VIP: Customers with at least 12 months of history and spending more than €5,000.
--Regular: Customers with at least 12 months of history but spending €5,000 or less.
--New: Customers with a lifespan less than 12 months.
--Find the total number of customers by each group

WITH customer_spending AS (
    SELECT
        c.customer_key,
        SUM(f.sales_amount) AS total_spending,
        MIN(order_date) AS first_order,
        MAX(order_date) AS last_order,
        DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_customers c
        ON f.customer_key = c.customer_key
    GROUP BY c.customer_key
)
SELECT 
    customer_segment,
    COUNT(customer_key) AS total_customers
FROM (
    SELECT 
        customer_key,
        CASE 
            WHEN lifespan >= 12 AND total_spending > 5000 THEN 'VIP'
            WHEN lifespan >= 12 AND total_spending <= 5000 THEN 'Regular'
            ELSE 'New'
        END AS customer_segment
    FROM customer_spending
) AS segmented_customers
GROUP BY customer_segment
ORDER BY total_customers DESC;













